# DO NOT TOUCH
config-version: 8

# 在以下情况下使用 'mmoitems.update-notify 'perm 节点通知玩家
# 如果有新的更新可供下载, 他们就会加入服务器。
# 更改时需要 /reload。
update-notify: true

# 启用/禁用迭代整个玩家库存的插件
# 而不仅仅是玩家的盔甲和持有的物品。
# 但是, 对于装饰品物品类型来说, 此选项是必需的
# 它可能会导致延迟和/或占用大量内存。
iterate-whole-inventory: false

# When this is set to true, skins can only be applied to an item ONCE. 
locked-skins: true

# 自 6.9.3 dev 版本开始, MMOItems 支持使用多个
# 同时使用 RPG 核心插件。然而, MMOItems 需要一个
# 用于挂钩关卡、类等的特定插件。
#
# 可用插件: 
# - MMOCORE (level, class, mana, stamina)
# - HEROES (level, class, mana, stamina)
# - SKILLAPI or PROSKILLAPI (level, class, mana)
# - RPGPLAYERLEVELING (level, mana, power)
# - RACESANDCLASSES (level, class, mana)
# - BATTLELEVELS (level)
# - MCMMO (power level)
# - MCRPG (power level)
# - SKILLS or SKILLSPRO (class, level, mana)
# - AURELIUM_SKILLS (power level, mana)
preferred-rpg-provider: MMOCORE

# 默认情况下, 所有玩家库存都会更新
# 10 个刻度对应每秒 2 次库存更新。
inventory-update-delay: 10

# 生成物品时, 物品等级
# 必须与玩家等级大致匹配
# 否则玩家无法使用物品/获得无用的物品。
#
# 物品等级总是在某处
# 间隔 [玩家等级 -分布, 玩家等级 + 分布]
item-level-spread: 2

# 目前存在客户端 Minecraft 问题
# 左键单击a
fix-left-click-interact: false

# 当生成的物品没有等级时, 
# 这是它将使用的容量公式。
default-item-capacity:
    base: 3
    scale: 0
    spread: 0
    max-spread: 0

# 更改某些统计数据的默认值。这主要是
# 考虑非目标武器, 如法杖、步枪...
default:
    attack-speed: 0.67
    range: 16
    blunt-rating: 33
    recoil: 0.1

# 更改此选项时重新启动服务器
dropped-items:

    # Items glow based on their tier
    tier-glow: true

    # Display item name over the dropped item
    hints: true

# 某些物品统计数据 (例如 '命令 '或 NBTTag) 可能会被滥用以成为操作。
# 你可以给这些统计数据绑定特定的权限来限制它们的版本。
# 您需要一个支持 Vault 的烫发插件才能使该选项发挥作用。
# 对应的权限为 'mmoitems.edit.op '。
op-item-stats:
    enabled: false
    stats:
        - COMMANDS
        - CUSTOM_NBT

item-upgrading:

    # 显示升级物品的名称后缀。
    name-suffix: ' &8(&e+#lvl#&8)'

    # 是否显示在物品名称或背景知识中
    # 如果玩家可以使用物品重命名, 则禁用。
    # 如果设置为 'false ', 请记住包含
    # %upgrade_level% 在你的物品传说中。
    display-in-name: true

    # 是否显示哪个
    # 传说中的统计数据发生了变化。
    display-stat-changes: false
    stat-change-suffix: ' &8(<p>#stat#&8)'
    stat-change-positive: '&a'
    stat-change-negative: '&c'

stats-displaying:

    # This will be a prefix to numeric stats,
    # changing their color when they are undesirable.
    color-positive: ''
    color-negative: ''

    # When items with RNG are displayed in crafting
    # stations, this is the separator between the low
    # and high bound:  Attack Damage  +5⎓7.5
    range-dash: '⎓'

soulbound:

    # Edit soulbound damage when players try to use
    # items which are not bound to themselves.
    damage:
        base: 1
        per-lvl: 1

    # Whether or not soulbound items should be
    # kept when a player dies.
    keep-on-death: true

    # Whether or not soulbound item can be
    # dropped by the player
    can-drop: true

# Enable, disable, and customize the weapon effects here.
# Weapon effects depend on the item type & type set.
item-ability:
    staff:
        enabled: true
        cooldown: 30
        power: 1
    gauntlet:
        enabled: true
        cooldown: 60
        power: 1
    blunt:
        aoe:
            enabled: true
            cooldown: 2
        stun:
            enabled: true
            chance: 5
            cooldown: 30
            power: 1
    slashing:
        enabled: true
        cooldown: 2
    piercing:
        enabled: true
        cooldown: 4

gem-sockets:

    # Define the text you need to enter in the
    # item gem sockets if you want to create an
    # uncolored gem socket i.e a socket for any type of gem.
    uncolored: 'Uncolored'

custom-blocks:

    # Whether or not custom blocks should
    # generate in the world according to
    # their generation template.
    enable-world-gen: false

    # Whether or not to remove mushroom block drops
    # from the droplist when mining a mushroom block
    # with silk-touch.
    # HIGHLY Recommended for servers that use
    # custom blocks, as the mushroom blocks can BREAK everything.
    replace-mushroom-drops: true

# Use this option if your chat management plugin is having
# conflicts with the MMOItems chat input feature. This will
# bring up an anvil GUI which you can input text in instead
# of using the chat.
anvil-text-input: false

# When set to true, players CANNOT upgrade an item if the
# specs (level, profession requirements) the item WOULD
# have if it were upgraded are too high for the player.
item-upgrade-requirements-check: true

# Players can't use their weapon/abilities when holding
# two-handed item and one other item simultaneously.
# When toggled off, players still receive slow 4.
two-handed-item-restriction: true

# You can select what char will be used to create
# the item ability cooldown progress bar.
cooldown-progress-bar-char: █

# Displays a message on the action bar instead of on the chat.
# Can be used to reduce chat spam.
# Might interfere with other action bar plugins.
action-bar-display:
    ability-cooldown: true
    item-cooldown: true
    not-enough-mana: true
    not-enough-stamina: true
    two-handed: true
    cant-use-item: true
    mitigation: true
    item-break: false

recipes:

    # Enables the vanilla recipe book for MMOItems recipes
    use-recipe-book: true

# "repair" prevents players from repairing MMOItems.
# "smelt" prevents players from smelting MMOItems.
# 'enchant" disables enchanting for MMOItems.
# "craft" prevents players from using MMOItems as ingredients.
# "arrow-shooting" prevents players from shooting any MMOItem that is an arrow.
disable-interactions:
    interact: false
    repair: false
    enchant: false
    smelt: false
    smith: false
    craft: false
    arrow-shooting: false

# Block types that can't be broken by an ability/item effect
block-blacklist:
    - OBSIDIAN

# Allows/disables the permissions needed in order to use items/abilities.
# General permission node for abilities: mmoitems.ability.ability-id
# Ex: - mmoitems.ability.fire-meteor
#     - mmoitems.ability.slow
#     - mmoitems.ability.cursed-fangs
#     etc.
permissions:
    abilities: false
    items: true

#
# When item stats has a numeric range of possibilities.
# attack-damage:
#    base: 10
#    spread: 1
#
# Using the spread, a level, and a random number, we
# obtain a random number (very related to the spread): 1.7
#
# If additive-spread-formula is true, this is added to the base:
#    RESULT: 10 + 1.7  =  11.7 attack damage
#
# If additive-spread-formula is false, this is multiplied to the base:
#    RESULT: 10 * 1.7  =  17 attack damage
#
additive-spread-formula: false

# Disables non MMOItems from being crafted in the vanilla workbench.
# Add [] if the list is empty.
disable-vanilla-recipes: []
# - DIAMOND_PICKAXE
# - IRON_BLOCK

# Options for the Item Revision System
item-revision:

    # Unsocketing gems picks them up with the stats they had
    # when first put into the item, disable this option to
    # force them to be regenerated.
    regenerate-gems-when-unsocketed: false

    # Legacy option to carry tiers over, will take precedence
    # If not specified next to the other keep- flags.
    keep-tiers: true

    # If an item is updated, and the new version does not
    # keep its gems, this will give the gems back to the
    # player so that they don't get lost forever.
    drop-extra-gems: true

    # When keeping lore data, only lore that starts with this
    # will actually be kept.
    kept-lore-prefix: '&7'

    # Whether or not specific stats should be kept
    # when an item is updated to latest revision.
    keep-data:

        # Name of the item, usually renamed via anvil
        display-name: true

        # Enchantments put on the item by the player
        enchantments: true

        # Soulbound applied to the item
        soulbound: true

        # Gems on the item
        gems: true

        # Upgrade level of the item
        upgrades: true

        # Specific lore lines of the item...
        # Warning, this prevents stats in the lore from updating visually!
        lore: false

        # Data that may have been put there by external plugins.
        exsh: true

        # Stats handled by RNG will be rerolled
        reroll: false

        # Modifiers of items ~ Sharp, Light, Heavy, Arcane
        modifications: true

        # Skins applied by MMOItems
        skins: true

        # Tier of the item
        tier: true

        # Third party plugin compatibility
        advanced-enchantments: true

    # Whether specific stats should be kept when gemstones
    # within an item are updated to the latest revision.
    keep-gem-data:

        # Name of the item, usually renamed via anvil
        display-name: true

        # Enchantments put on the item by the player
        enchantments: true

        # Specific lore lines of the item...
        # Warning, this prevents stats in the lore from updating visually!
        lore: false

        # Stats handled by RNG will be rerolled
        reroll: false

    phat-loots:
        display-name: false
        enchantments: false
        soulbound: false
        gems: true
        upgrades: false
        lore: false
        exsh: false
        tier: true
        skins: false
        reroll: true
        modifications: false
        advanced-enchantments: false

    # These will not update at all in PhatLoots, for
    # compatibility with quest plugins that check for
    # exact NBT
    disable-phat-loot:
        - MANGO
        - STEEL_HELMET

    # Here you can disable individual events for when
    # Items should update when a higher revision ID is found
    disable-on:
        pickup: false
        craft: true # 'true' recommended
        click: false
        join: false

# Offset is the distance traveled on X and Y coordinates
# Height is the Y velocity coordinate. Lootsplosions
# only trigger with MythicMobs monsters.
# Requires a SERVER reload when changed.
lootsplosion:
    enabled: true
    color: true
    offset: .2
    height: .6

# When Upgrading meets Gems, one must decide if
# gems' stats will increase as well.
gem-upgrade-default: 'NEVER'

# This option allows you to disable the ability to
# use MMOItems that have been removed from your config.
disable-removed-items: true
